---

# TODO: Put in Ansible config for the initial manual config that I did as well
# Doing that is kinda fragile but can help prevent drift

- name: Install BIND
  package: name={{ item }} state=latest
  with_items:
    - bind
    - bind-utils
  notify: restart named
  tags: named

- name: Create zones directory
  file: path=/etc/named/zones state=directory owner=root group=named mode=0770
  tags: named

- name: Install BIND config files
  template: src=bind/{{ item.src }} dest={{ item.dest }} owner=root group=named mode=0660
  with_items:
    - { src: "named.conf.j2", dest: "/etc/named.conf" }
    - { src: "db.cluster.dns.j2", dest: "/etc/named/zones/db.{{ cluster_domain }}" }
    - { src: "db.reverse4.dns.j2", dest: "/etc/named/zones/db.{{ cluster_revdns4 }}" }
  notify: restart named
  tags: named

- name: Allow BIND through the firewall
  firewalld: service=dns permanent=yes immediate=yes state=enabled zone={{ fedora_firewalld_zone }}
  tags: named

- name: Enable BIND
  systemd: name=named state=started enabled=yes
  tags: named

# Stupid bug means can't use nmcli module
# https://github.com/ansible/ansible/issues/48055
- name: Use BIND for local DNS resolution
  # nmcli: conn_name="{{ ethernet_connection_name }}" dns4="127.0.0.1"
  command: nmcli con mod '{{ ethernet_connection_name }}' ipv4.dns "127.0.0.1"
  tags: named

- name: Install DHCPD
  package: name=dhcp state=latest
  notify: restart dhcpd
  tags: dhcpd

- name: Install DHCPD config files
  template: src=dhcpd/dhcpd.conf.j2 dest=/etc/dhcp/dhcpd.conf owner=root group=root mode=0600
  notify: restart dhcpd
  tags: dhcpd

- name: Allow DHCPD through the firewall
  firewalld: service=dhcp permanent=yes immediate=yes state=enabled zone={{ fedora_firewalld_zone }}
  tags: dhcpd

- name: Enable DHCPD
  systemd: name=dhcpd state=started enabled=yes
  tags: dhcpd

# - name: Install tools required for Das U-Boot
#   package: name=uboot-tools state=latest

- name: Install tftp server
  package: name=tftp-server state=latest
  notify: restart tftpd
  tags: tftpd

- name: Create tftp service override directory
  file: path=/etc/systemd/system/tftp.service.d state=directory owner=root group=root mode=0755
  tags: tftpd

- name: Install tftp override settings
  template: src=tftpd/tftp.service.overrride.j2 dest=/etc/systemd/system/tftp.service.d/override.conf
  notify: restart tftpd
  tags: tftpd

- name: Retrieve kernel and initrd
  get_url: url={{ item.url }} dest={{ item.dest }} mode=0644
  with_items:
    - { url: "{{ fedora_armhfp_kernel }}", dest: "{{ tftp_kernel }}" }
    - { url: "{{ fedora_armhfp_initrd }}", dest: "{{ tftp_initrd }}" }
    - { url: "{{ fedora_armhfp_dtb }}", dest: "{{ tftp_dtb }}" }
  tags: tftpd

- name: Install pxelinux configuration
  template: src=tftpd/pexelinux.default-arm.j2 dest={{ tftp_pxelinuxcfg }} mode=0644
  tags: tftpd

- name: Allow tftpd through the firewall
  firewalld: service=tftp permanent=yes immediate=yes state=enabled zone={{ fedora_firewalld_zone }}
  tags: tftpd

- name: Enable tftpd
  systemd: name=tftp state=started enabled=yes
  tags: tftpd

- name: Install egoboost script
  template: src=egoboost/egoboost.py.j2 dest=/usr/local/bin/egoboost.py mode=0755 owner=root group=root
  tags: egoboost

- name: Install egoboost prereq packages
  package: name={{ item }} state=latest
  with_items:
    # - arm-image-installer  # not necessary for our script, but helpful for whole FS on SD card
    - uboot-images-armv7
  tags: egoboost

- name: Create egoboost lib directory
  file: path={{ egoboost_lib_directory }} state=directory mode=0755 owner=root group=root
  tags: egoboost

- name: Install egoboost firmware etc
  copy: src={{ item }} dest={{ egoboost_lib_directory }}/ mode=0644 owner=root group=root
  with_fileglob: egoboost/*
  tags: egoboost

- name: Install ego U-Boot script script
  template: src=egoboost/ego.uenv.txt.j2 dest={{ egoboost_lib_directory }}/ego.uenv.txt mode=0644 owner=root group=root
  tags: egoboost

- name: Install required egobuilder packages
  package: name={{ item }} state=latest
  with_items:
    - libvirt
    - libguestfs-tools
  tags: egobuilder
